### ISSUE TITLE
"Unknown error occured"

### ISSUE THREAD

**Issue by anneke** [verbb/image-resizer#16]
Hi there,

I happily installed this plugin today, but whenever it starts to perform a resize action ("bulk resize" or when it should start processing a freshly uploaded picture), it gives the "Unknown error occured" error. 💔 

I know this is not very helpful, but the error message isn't either ;) Please let me know where I can find useful information.
I am on Craft CMS 2.6.2954 , PHP version 5.6.28 , ...

Ahh, I now found an error message "PHP exif extension is required to use the ExifMetadataReader". Could this be the culprit? :)

**Comment by engram-design** [comment]
Sorry for the delay, but I imagine that the exif extension might have something to do with it. If you're still having issues, happy to discuss further?

**Comment by asinnema** [comment]
Hi Josh, 

I was in touch with the webhost about installing - I think - imageOptim or the appropriate module you mentioned in your readme - on the server which I think was causing the problem. Unfortunately that is not an option for them so for now we will be unable to use your wonderful work :( thank you for getting back to me, keep doing the good work

Anneke

**Comment by engram-design** [comment]
Closing for now, but certainly worth noting for future reference.
