### ISSUE TITLE
Bulk Resize stops if a non-image exists in the directory

### ISSUE THREAD

**Issue by iainsaxon** [verbb/image-resizer#28]
First of all: thanks for creating this addon, it looks like it will elegantly solve a problem we have where our clients upload 10MB+ images that slow the site down when combined with image transforms :) .

We had an issue while running a Bulk Resize on a directory that contained a PDF or CSV file. In the Image Resize log we could see the "skipped-non-image" entry however the task would fail every time that file was processed. After stepping through the PHP I realised Craft was throwing an exception stemming from this line in the [ImageResizerTask](https://github.com/engram-design/ImageResizer/blob/master/imageresizer/tasks/ImageResizerTask.php#L57) and the exception was just being buried in the craft.log files:

````
list ($assetWidth, $assetHeight) = ImageHelper::getImageSize($path);
````

Even though the file cannot be processed as an image the function still tries to get the image dimensions.

To quickly get around this issue with the least amount of code change I came up with the following and created a PR:
https://github.com/engram-design/ImageResizer/pull/27

If the `craft()->imageResizer_resize->resize()` function returned false for any reason the task will early exit to prevent any further processing of a non-image and allow the Bulk Resize to continue.

**Comment by svenjungnickel** [comment]
Fixed in the latest [Craft2 branch](https://github.com/verbb/image-resizer/archive/craft-2.zip).
