### ISSUE TITLE
Resizing images from s3 source with "keepOriginals" flag breaks

### ISSUE THREAD

**Issue by leevigraham** [verbb/image-resizer#29]
I'm still trying to nail this bug down but from what I can see the filename is passed through to the resize function but Craft is using the asset id as the filename. This means the /originals path is broken.

**Comment by svenjungnickel** [comment]
Hey @leevigraham. Thanks for the issue. Unfortunately the handling of remote assets is a little tricky in craft2. Therefore I builded a fix in the latest [Craft2 branch](https://github.com/verbb/image-resizer/archive/craft-2.zip) that will skip remote asset sources.

That is better handled in craft3. The craft3 version will support resizing of remote volumes though.
