### ISSUE TITLE
'originals' folders don't get created on upload

### ISSUE THREAD

**Issue by pierrestoffe** [verbb/image-resizer#31]
I noticed that the _originals_ folder is not created at the time an image is uploaded, even though I have the _Non-destructive_ setting enabled. I only see it being creating when bulk-resizing images... but that's of course too late since the original file is gone at that point.

**Comment by pierrestoffe** [comment]
From what I understand, it is caused by the `$path` variable in the `resize` function that matches the runtime temp folder when the image is uploaded, while it matches the assets source folder when the bulk-resizing task is running.

**Comment by svenjungnickel** [comment]
Hey @pierrestoffe . Thanks for the issue. This is now fixed in the latest [Craft2 branch](https://github.com/verbb/image-resizer/archive/craft-2.zip)
