### ISSUE TITLE
Image getting stuck in storage>runtime>temp

### ISSUE THREAD

**Issue by terryupton** [verbb/image-resizer#33]
### Description
I have Resize on upload enabled and set to 2000w and 2000h - I can see the images uploaded and these appear as resized versions inside the craft storage>runtime>temp - but they don't get moved over to the assets folder and the bank-end results in the progress bar staying on the screen and nothing happening. I don't see any messages in the logs and I don't see any stuck tasks in the DB.

Working locally on MAMP Pro and I have tried both imagick and gd (although I suspect not an issue as the image is resized).

### Steps to reproduce

1. Upload the asset via the asset editor or the template
2. Image resized but stays inside : storage>runtime>temp

### Additional info

- Plugin version: 1.0.1 
- Craft version: 2.6.2997

**Comment by joshworden** [comment]
Experiencing the same issue.

**Comment by terryupton** [comment]
@joshworden in the end I switched my development to Homestead locally instead of MAMP Pro and the problem was resolved. I had countless issues with several plugins and terrible speeds with Craft overall using MAMP.

**Comment by joshworden** [comment]
Thanks. I've been putting Homestead off, but it's looking like it might be inevitable.

**Comment by terryupton** [comment]
I had too @joshworden - but I am very glad I made the switch now. It wasn't too difficult. I found this article very useful https://nystudio107.com/blog/local-development-with-vagrant-homestead

**Comment by engram-design** [comment]
Thanks for the feedback all, environmental issues are a bit of a tricky business to debug and test. Its indeed interesting that it processes the image, but is unable to move. However, its at this point that its Craft's responsibility to move the temp image into its proper place.

I would imagine there's no Image Resizer or Craft logs that are helpful?

**Comment by engram-design** [comment]
Closing - the Craft 2 version is no longer supported.
