### ISSUE TITLE
Uploading SVG with resize generates an error

### ISSUE THREAD

**Issue by GewoonRoy** [verbb/image-resizer#34]
### Description
When uploading an SVG file it will generate an error because the Craft/SvgImage has changed.

**Error occured:**
```
Call to undefined method Craft\SvgImage::setQuality() (/craft/plugins/imageresizer/services/ImageResizer_ResizeService.php:66)
```

### Steps to reproduce

1. Upload SVG file which needs to be resized on upload

### Additional info

- Plugin version: 1.0.0
- Craft version: 2.6.2997

**Comment by svenjungnickel** [comment]
Hey @GewoonRoy. Thanks for the issue. This is now fixed in the latest [Craft2 branch](https://github.com/verbb/image-resizer/archive/craft-2.zip)
